---
swagger: "2.0"
info:
  description: "A simple API"
  version: "0.0.1"
  title: "AD_API"
basePath: "/api"
schemes:
- "http"
consumes:
- "application/json"
paths:
  /groups:
    get:
      description: "Returns members of the group"
      operationId: "group_get"
      produces:
      - "application/json"
      parameters: []
      responses:
        200:
          description: "Success"
          schema:
            $ref: "#/definitions/Group"
      x-swagger-router-controller: "swagger_server.controllers.default_controller"
definitions:
  Group:
    type: "string"
